extensions = {'gcc': 'c',
              'c': 'c',
              'csharp': 'c#',
              'hs': 'haskell',
              'sbcl': 'common lisp',
              'clojure': 'clojure',
              'java': 'java',
              'tcl': 'tcl',
              'js': 'javascript',
              'javascript': 'javascript',
              'ocaml': 'ocaml',
              'perl': 'perl',
              'hack': 'php',
              'php': 'php',
              'python3': 'python',
              'jruby': 'ruby',
              'yarv': 'ruby',
              'scala': 'scala',
              'racket': 'scheme'}
